services:
  - type: web
    name: fularani-frontend
    env: static
    rootDir: app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
